### ISSUE TITLE
Mismatching between codes and paper

### ISSUE THREAD

**Issue by zhenglinpan** [Chanuku/Semi_ref2sketch_code#5]
Hi👋I noticed there's a small mismatching between codes and paper.
In the Fig.2. from [the paper published](https://dl.acm.org/doi/10.1145/3592392), there is a resnet in Gc during reconstruction,
![image](https://github.com/Chanuku/Semi_ref2sketch_code/assets/35617532/560dfb8f-8d07-4d5c-8e54-4f0f79229ddf)

However this resnet is not implemented in your codes, as per https://github.com/Chanuku/Semi_ref2sketch_code/blob/main/models/networks.py#L369,
the encoder is followed directly by a decoder.

May I kindly ask has the resnet been removed for the final implementation for your paper?

**Comment by zhenglinpan** [comment]
Also, the resnet block used in the implementation seems to be inactivated for the output, will this impose an adverse impact for the result?

**Comment by Chanuku** [comment]
Hi, great thanks for checking our code!
It seems to be that we have little mistake while cleaning up the code for github upload. 
We will going to fix it as soon as possible.
However, the performance for without resblock to reconstruction domain is almost same which is not affecting to perfomance.

Moreover, while the " self.status == 'ref_unpair_cbam_cat' " the resnetblock is activated 
https://github.com/Chanuku/Semi_ref2sketch_code/blob/main/models/networks.py#L443

**Comment by zhenglinpan** [comment]
Hi Chanuku, thanks for your response!

Sure no problem! I'll keep up with your revised codes!

And yes, the code goes exactly what paper says for Gs, i.e. the first part of the network where cbam is engaged, it's just the matter for the second part that differs from the paper LOL.

It's good to know the activation does not affect the final result.

Thanks for your response again, I'll pay attention to your update.

**Comment by Chanuku** [comment]
Hi I just fixed the code and checked no problem with current pre-trained checkpoint

https://github.com/Chanuku/Semi_ref2sketch_code/blob/main/models/networks.py#L467

Thanks
